/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MockRouter,
  MockRouterInterface,
} from "../../MockRouter.sol/MockRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "mockSwap",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102a5806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80637f24febb14610030575b600080fd5b61004361003e3660046101ef565b610045565b005b6040516323b872dd60e01b8152336004820152306024820152604481018490526001600160a01b038616906323b872dd906064016020604051808303816000875af1158015610098573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100bc9190610246565b61010d5760405162461bcd60e51b815260206004820152601760248201527f4d6f636b526f757465723a2070756c6c206661696c656400000000000000000060448201526064015b60405180910390fd5b60405163a9059cbb60e01b81526001600160a01b0382811660048301526024820184905285169063a9059cbb906044016020604051808303816000875af115801561015c573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101809190610246565b6101cc5760405162461bcd60e51b815260206004820152601960248201527f4d6f636b526f757465723a207061796f7574206661696c6564000000000000006044820152606401610104565b5050505050565b80356001600160a01b03811681146101ea57600080fd5b919050565b600080600080600060a0868803121561020757600080fd5b610210866101d3565b945061021e602087016101d3565b9350604086013592506060860135915061023a608087016101d3565b90509295509295909350565b60006020828403121561025857600080fd5b8151801515811461026857600080fd5b939250505056fea2646970667358221220ff845620ab07c5cf5edcab60bfde3924cbfdfe90ad270a9c2a53606cfe3958dd64736f6c63430008140033";

type MockRouterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockRouterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockRouter__factory extends ContractFactory {
  constructor(...args: MockRouterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockRouter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockRouter__factory {
    return super.connect(runner) as MockRouter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockRouterInterface {
    return new Interface(_abi) as MockRouterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MockRouter {
    return new Contract(address, _abi, runner) as unknown as MockRouter;
  }
}
