/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FluxAgentRegistry {
  export type AgentStruct = {
    agentWallet: AddressLike;
    owner: AddressLike;
    perTxCap: BigNumberish;
    dailyCap: BigNumberish;
    totalCap: BigNumberish;
    spentToday: BigNumberish;
    spentTotal: BigNumberish;
    expiry: BigNumberish;
    dayStart: BigNumberish;
    status: BigNumberish;
  };

  export type AgentStructOutput = [
    agentWallet: string,
    owner: string,
    perTxCap: bigint,
    dailyCap: bigint,
    totalCap: bigint,
    spentToday: bigint,
    spentTotal: bigint,
    expiry: bigint,
    dayStart: bigint,
    status: bigint
  ] & {
    agentWallet: string;
    owner: string;
    perTxCap: bigint;
    dailyCap: bigint;
    totalCap: bigint;
    spentToday: bigint;
    spentTotal: bigint;
    expiry: bigint;
    dayStart: bigint;
    status: bigint;
  };
}

export interface FluxAgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agents"
      | "allowlisted"
      | "blocklisted"
      | "getAgent"
      | "isPayable"
      | "nextAgentId"
      | "pause"
      | "recordExternalSpend"
      | "recordPayment"
      | "registerAgent"
      | "restrictToAllowlist"
      | "resume"
      | "revoke"
      | "setAllowlisted"
      | "setBlocklisted"
      | "setRestrictToAllowlist"
      | "updateCaps"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentPaused"
      | "AgentPayment"
      | "AgentRegistered"
      | "AgentResumed"
      | "AgentRevoked"
      | "AllowlistModeSet"
      | "CapsUpdated"
      | "RecipientListUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allowlisted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blocklisted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPayable",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextAgentId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "recordExternalSpend",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordPayment",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "restrictToAllowlist",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resume",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revoke",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowlisted",
    values: [BigNumberish, AddressLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setBlocklisted",
    values: [BigNumberish, AddressLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setRestrictToAllowlist",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCaps",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allowlisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blocklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPayable", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextAgentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordExternalSpend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "restrictToAllowlist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resume", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAllowlisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBlocklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRestrictToAllowlist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateCaps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace AgentPausedEvent {
  export type InputTuple = [agentId: BigNumberish];
  export type OutputTuple = [agentId: bigint];
  export interface OutputObject {
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentPaymentEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    to: AddressLike,
    amount: BigNumberish,
    spentToday: BigNumberish,
    spentTotal: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    to: string,
    amount: bigint,
    spentToday: bigint,
    spentTotal: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    to: string;
    amount: bigint;
    spentToday: bigint;
    spentTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    owner: AddressLike,
    agentWallet: AddressLike,
    perTxCap: BigNumberish,
    dailyCap: BigNumberish,
    totalCap: BigNumberish,
    expiry: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    owner: string,
    agentWallet: string,
    perTxCap: bigint,
    dailyCap: bigint,
    totalCap: bigint,
    expiry: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    owner: string;
    agentWallet: string;
    perTxCap: bigint;
    dailyCap: bigint;
    totalCap: bigint;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentResumedEvent {
  export type InputTuple = [agentId: BigNumberish];
  export type OutputTuple = [agentId: bigint];
  export interface OutputObject {
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRevokedEvent {
  export type InputTuple = [agentId: BigNumberish];
  export type OutputTuple = [agentId: bigint];
  export interface OutputObject {
    agentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AllowlistModeSetEvent {
  export type InputTuple = [agentId: BigNumberish, restricted: boolean];
  export type OutputTuple = [agentId: bigint, restricted: boolean];
  export interface OutputObject {
    agentId: bigint;
    restricted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapsUpdatedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    perTxCap: BigNumberish,
    dailyCap: BigNumberish,
    totalCap: BigNumberish,
    expiry: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    perTxCap: bigint,
    dailyCap: bigint,
    totalCap: bigint,
    expiry: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    perTxCap: bigint;
    dailyCap: bigint;
    totalCap: bigint;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecipientListUpdatedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    recipient: AddressLike,
    allowlist: boolean,
    value: boolean
  ];
  export type OutputTuple = [
    agentId: bigint,
    recipient: string,
    allowlist: boolean,
    value: boolean
  ];
  export interface OutputObject {
    agentId: bigint;
    recipient: string;
    allowlist: boolean;
    value: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FluxAgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): FluxAgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: FluxAgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        agentWallet: string;
        owner: string;
        perTxCap: bigint;
        dailyCap: bigint;
        totalCap: bigint;
        spentToday: bigint;
        spentTotal: bigint;
        expiry: bigint;
        dayStart: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  allowlisted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  blocklisted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getAgent: TypedContractMethod<
    [agentId: BigNumberish],
    [FluxAgentRegistry.AgentStructOutput],
    "view"
  >;

  isPayable: TypedContractMethod<
    [agentId: BigNumberish, to: AddressLike, amount: BigNumberish],
    [[boolean, string] & { ok: boolean; reason: string }],
    "view"
  >;

  nextAgentId: TypedContractMethod<[], [bigint], "view">;

  pause: TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;

  recordExternalSpend: TypedContractMethod<
    [agentId: BigNumberish, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordPayment: TypedContractMethod<
    [agentId: BigNumberish, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerAgent: TypedContractMethod<
    [
      agentWallet: AddressLike,
      perTxCap: BigNumberish,
      dailyCap: BigNumberish,
      totalCap: BigNumberish,
      expiry: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  restrictToAllowlist: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  resume: TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;

  revoke: TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;

  setAllowlisted: TypedContractMethod<
    [agentId: BigNumberish, addrs: AddressLike[], allowed: boolean],
    [void],
    "nonpayable"
  >;

  setBlocklisted: TypedContractMethod<
    [agentId: BigNumberish, addrs: AddressLike[], blocked: boolean],
    [void],
    "nonpayable"
  >;

  setRestrictToAllowlist: TypedContractMethod<
    [agentId: BigNumberish, restricted: boolean],
    [void],
    "nonpayable"
  >;

  updateCaps: TypedContractMethod<
    [
      agentId: BigNumberish,
      perTxCap: BigNumberish,
      dailyCap: BigNumberish,
      totalCap: BigNumberish,
      expiry: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        agentWallet: string;
        owner: string;
        perTxCap: bigint;
        dailyCap: bigint;
        totalCap: bigint;
        spentToday: bigint;
        spentTotal: bigint;
        expiry: bigint;
        dayStart: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "allowlisted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "blocklisted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [FluxAgentRegistry.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPayable"
  ): TypedContractMethod<
    [agentId: BigNumberish, to: AddressLike, amount: BigNumberish],
    [[boolean, string] & { ok: boolean; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextAgentId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recordExternalSpend"
  ): TypedContractMethod<
    [agentId: BigNumberish, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordPayment"
  ): TypedContractMethod<
    [agentId: BigNumberish, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [
      agentWallet: AddressLike,
      perTxCap: BigNumberish,
      dailyCap: BigNumberish,
      totalCap: BigNumberish,
      expiry: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "restrictToAllowlist"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "resume"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revoke"
  ): TypedContractMethod<[agentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAllowlisted"
  ): TypedContractMethod<
    [agentId: BigNumberish, addrs: AddressLike[], allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBlocklisted"
  ): TypedContractMethod<
    [agentId: BigNumberish, addrs: AddressLike[], blocked: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRestrictToAllowlist"
  ): TypedContractMethod<
    [agentId: BigNumberish, restricted: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCaps"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      perTxCap: BigNumberish,
      dailyCap: BigNumberish,
      totalCap: BigNumberish,
      expiry: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AgentPaused"
  ): TypedContractEvent<
    AgentPausedEvent.InputTuple,
    AgentPausedEvent.OutputTuple,
    AgentPausedEvent.OutputObject
  >;
  getEvent(
    key: "AgentPayment"
  ): TypedContractEvent<
    AgentPaymentEvent.InputTuple,
    AgentPaymentEvent.OutputTuple,
    AgentPaymentEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentResumed"
  ): TypedContractEvent<
    AgentResumedEvent.InputTuple,
    AgentResumedEvent.OutputTuple,
    AgentResumedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRevoked"
  ): TypedContractEvent<
    AgentRevokedEvent.InputTuple,
    AgentRevokedEvent.OutputTuple,
    AgentRevokedEvent.OutputObject
  >;
  getEvent(
    key: "AllowlistModeSet"
  ): TypedContractEvent<
    AllowlistModeSetEvent.InputTuple,
    AllowlistModeSetEvent.OutputTuple,
    AllowlistModeSetEvent.OutputObject
  >;
  getEvent(
    key: "CapsUpdated"
  ): TypedContractEvent<
    CapsUpdatedEvent.InputTuple,
    CapsUpdatedEvent.OutputTuple,
    CapsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RecipientListUpdated"
  ): TypedContractEvent<
    RecipientListUpdatedEvent.InputTuple,
    RecipientListUpdatedEvent.OutputTuple,
    RecipientListUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentPaused(uint256)": TypedContractEvent<
      AgentPausedEvent.InputTuple,
      AgentPausedEvent.OutputTuple,
      AgentPausedEvent.OutputObject
    >;
    AgentPaused: TypedContractEvent<
      AgentPausedEvent.InputTuple,
      AgentPausedEvent.OutputTuple,
      AgentPausedEvent.OutputObject
    >;

    "AgentPayment(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      AgentPaymentEvent.InputTuple,
      AgentPaymentEvent.OutputTuple,
      AgentPaymentEvent.OutputObject
    >;
    AgentPayment: TypedContractEvent<
      AgentPaymentEvent.InputTuple,
      AgentPaymentEvent.OutputTuple,
      AgentPaymentEvent.OutputObject
    >;

    "AgentRegistered(uint256,address,address,uint256,uint256,uint256,uint64)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentResumed(uint256)": TypedContractEvent<
      AgentResumedEvent.InputTuple,
      AgentResumedEvent.OutputTuple,
      AgentResumedEvent.OutputObject
    >;
    AgentResumed: TypedContractEvent<
      AgentResumedEvent.InputTuple,
      AgentResumedEvent.OutputTuple,
      AgentResumedEvent.OutputObject
    >;

    "AgentRevoked(uint256)": TypedContractEvent<
      AgentRevokedEvent.InputTuple,
      AgentRevokedEvent.OutputTuple,
      AgentRevokedEvent.OutputObject
    >;
    AgentRevoked: TypedContractEvent<
      AgentRevokedEvent.InputTuple,
      AgentRevokedEvent.OutputTuple,
      AgentRevokedEvent.OutputObject
    >;

    "AllowlistModeSet(uint256,bool)": TypedContractEvent<
      AllowlistModeSetEvent.InputTuple,
      AllowlistModeSetEvent.OutputTuple,
      AllowlistModeSetEvent.OutputObject
    >;
    AllowlistModeSet: TypedContractEvent<
      AllowlistModeSetEvent.InputTuple,
      AllowlistModeSetEvent.OutputTuple,
      AllowlistModeSetEvent.OutputObject
    >;

    "CapsUpdated(uint256,uint256,uint256,uint256,uint64)": TypedContractEvent<
      CapsUpdatedEvent.InputTuple,
      CapsUpdatedEvent.OutputTuple,
      CapsUpdatedEvent.OutputObject
    >;
    CapsUpdated: TypedContractEvent<
      CapsUpdatedEvent.InputTuple,
      CapsUpdatedEvent.OutputTuple,
      CapsUpdatedEvent.OutputObject
    >;

    "RecipientListUpdated(uint256,address,bool,bool)": TypedContractEvent<
      RecipientListUpdatedEvent.InputTuple,
      RecipientListUpdatedEvent.OutputTuple,
      RecipientListUpdatedEvent.OutputObject
    >;
    RecipientListUpdated: TypedContractEvent<
      RecipientListUpdatedEvent.InputTuple,
      RecipientListUpdatedEvent.OutputTuple,
      RecipientListUpdatedEvent.OutputObject
    >;
  };
}
