/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FluxSettlement {
  export type AgentStruct = {
    label: string;
    budgetCap: BigNumberish;
    spent: BigNumberish;
    active: boolean;
    registeredAt: BigNumberish;
  };

  export type AgentStructOutput = [
    label: string,
    budgetCap: bigint,
    spent: bigint,
    active: boolean,
    registeredAt: bigint
  ] & {
    label: string;
    budgetCap: bigint;
    spent: bigint;
    active: boolean;
    registeredAt: bigint;
  };

  export type StreamStruct = {
    sender: AddressLike;
    recipient: AddressLike;
    totalAmount: BigNumberish;
    released: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    cancelled: boolean;
  };

  export type StreamStructOutput = [
    sender: string,
    recipient: string,
    totalAmount: bigint,
    released: bigint,
    startTime: bigint,
    endTime: bigint,
    cancelled: boolean
  ] & {
    sender: string;
    recipient: string;
    totalAmount: bigint;
    released: bigint;
    startTime: bigint;
    endTime: bigint;
    cancelled: boolean;
  };
}

export interface FluxSettlementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOM"
      | "FEE_BPS"
      | "agentList"
      | "agentPay"
      | "agents"
      | "batchSettle"
      | "cancelStream"
      | "claimableAmount"
      | "createStream"
      | "depositForAgents"
      | "getAgent"
      | "getAllAgents"
      | "getStats"
      | "getStream"
      | "owner"
      | "registerAgent"
      | "streams"
      | "totalBatches"
      | "totalFeesAccrued"
      | "totalSettledVolume"
      | "totalStreams"
      | "updateAgent"
      | "usdc"
      | "withdrawFees"
      | "withdrawFromStream"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentPayment"
      | "AgentRegistered"
      | "AgentUpdated"
      | "BatchSettled"
      | "FeesWithdrawn"
      | "StreamCancelled"
      | "StreamCreated"
      | "StreamWithdrawn"
  ): EventFragment;

  encodeFunctionData(functionFragment: "BPS_DENOM", values?: undefined): string;
  encodeFunctionData(functionFragment: "FEE_BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "agentList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentPay",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "batchSettle",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelStream",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createStream",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositForAgents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAgents",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getStream",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "streams",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalBatches",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeesAccrued",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSettledVolume",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalStreams",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateAgent",
    values: [AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFromStream",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "BPS_DENOM", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "FEE_BPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agentList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agentPay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchSettle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositForAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStream", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "streams", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalBatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesAccrued",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSettledVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStreams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFromStream",
    data: BytesLike
  ): Result;
}

export namespace AgentPaymentEvent {
  export type InputTuple = [
    agent: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [agent: string, recipient: string, amount: bigint];
  export interface OutputObject {
    agent: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agent: AddressLike,
    label: string,
    budgetCap: BigNumberish
  ];
  export type OutputTuple = [agent: string, label: string, budgetCap: bigint];
  export interface OutputObject {
    agent: string;
    label: string;
    budgetCap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentUpdatedEvent {
  export type InputTuple = [
    agent: AddressLike,
    newBudgetCap: BigNumberish,
    active: boolean
  ];
  export type OutputTuple = [
    agent: string,
    newBudgetCap: bigint,
    active: boolean
  ];
  export interface OutputObject {
    agent: string;
    newBudgetCap: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchSettledEvent {
  export type InputTuple = [
    sender: AddressLike,
    recipientCount: BigNumberish,
    totalUSDC: BigNumberish,
    fee: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    recipientCount: bigint,
    totalUSDC: bigint,
    fee: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    sender: string;
    recipientCount: bigint;
    totalUSDC: bigint;
    fee: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesWithdrawnEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamCancelledEvent {
  export type InputTuple = [
    id: BigNumberish,
    sender: AddressLike,
    refund: BigNumberish
  ];
  export type OutputTuple = [id: bigint, sender: string, refund: bigint];
  export interface OutputObject {
    id: bigint;
    sender: string;
    refund: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    sender: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    sender: string,
    recipient: string,
    amount: bigint,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    id: bigint;
    sender: string;
    recipient: string;
    amount: bigint;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamWithdrawnEvent {
  export type InputTuple = [
    id: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, recipient: string, amount: bigint];
  export interface OutputObject {
    id: bigint;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FluxSettlement extends BaseContract {
  connect(runner?: ContractRunner | null): FluxSettlement;
  waitForDeployment(): Promise<this>;

  interface: FluxSettlementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOM: TypedContractMethod<[], [bigint], "view">;

  FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  agentList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  agentPay: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean, bigint] & {
        label: string;
        budgetCap: bigint;
        spent: bigint;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  batchSettle: TypedContractMethod<
    [recipients: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  cancelStream: TypedContractMethod<
    [streamId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimableAmount: TypedContractMethod<
    [streamId: BigNumberish],
    [bigint],
    "view"
  >;

  createStream: TypedContractMethod<
    [
      recipient: AddressLike,
      amount: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  depositForAgents: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAgent: TypedContractMethod<
    [agent: AddressLike],
    [FluxSettlement.AgentStructOutput],
    "view"
  >;

  getAllAgents: TypedContractMethod<[], [string[]], "view">;

  getStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        volume: bigint;
        fees: bigint;
        batches: bigint;
        streamCount: bigint;
        agentCount: bigint;
      }
    ],
    "view"
  >;

  getStream: TypedContractMethod<
    [streamId: BigNumberish],
    [FluxSettlement.StreamStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerAgent: TypedContractMethod<
    [agent: AddressLike, label: string, budgetCap: BigNumberish],
    [void],
    "nonpayable"
  >;

  streams: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        sender: string;
        recipient: string;
        totalAmount: bigint;
        released: bigint;
        startTime: bigint;
        endTime: bigint;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  totalBatches: TypedContractMethod<[], [bigint], "view">;

  totalFeesAccrued: TypedContractMethod<[], [bigint], "view">;

  totalSettledVolume: TypedContractMethod<[], [bigint], "view">;

  totalStreams: TypedContractMethod<[], [bigint], "view">;

  updateAgent: TypedContractMethod<
    [agent: AddressLike, newBudgetCap: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  withdrawFromStream: TypedContractMethod<
    [streamId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "agentPay"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean, bigint] & {
        label: string;
        budgetCap: bigint;
        spent: bigint;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "batchSettle"
  ): TypedContractMethod<
    [recipients: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelStream"
  ): TypedContractMethod<[streamId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimableAmount"
  ): TypedContractMethod<[streamId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "createStream"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      amount: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositForAgents"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agent: AddressLike],
    [FluxSettlement.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllAgents"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        volume: bigint;
        fees: bigint;
        batches: bigint;
        streamCount: bigint;
        agentCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStream"
  ): TypedContractMethod<
    [streamId: BigNumberish],
    [FluxSettlement.StreamStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [agent: AddressLike, label: string, budgetCap: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "streams"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        sender: string;
        recipient: string;
        totalAmount: bigint;
        released: bigint;
        startTime: bigint;
        endTime: bigint;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalBatches"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFeesAccrued"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSettledVolume"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalStreams"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateAgent"
  ): TypedContractMethod<
    [agent: AddressLike, newBudgetCap: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFromStream"
  ): TypedContractMethod<[streamId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AgentPayment"
  ): TypedContractEvent<
    AgentPaymentEvent.InputTuple,
    AgentPaymentEvent.OutputTuple,
    AgentPaymentEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentUpdated"
  ): TypedContractEvent<
    AgentUpdatedEvent.InputTuple,
    AgentUpdatedEvent.OutputTuple,
    AgentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BatchSettled"
  ): TypedContractEvent<
    BatchSettledEvent.InputTuple,
    BatchSettledEvent.OutputTuple,
    BatchSettledEvent.OutputObject
  >;
  getEvent(
    key: "FeesWithdrawn"
  ): TypedContractEvent<
    FeesWithdrawnEvent.InputTuple,
    FeesWithdrawnEvent.OutputTuple,
    FeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "StreamCancelled"
  ): TypedContractEvent<
    StreamCancelledEvent.InputTuple,
    StreamCancelledEvent.OutputTuple,
    StreamCancelledEvent.OutputObject
  >;
  getEvent(
    key: "StreamCreated"
  ): TypedContractEvent<
    StreamCreatedEvent.InputTuple,
    StreamCreatedEvent.OutputTuple,
    StreamCreatedEvent.OutputObject
  >;
  getEvent(
    key: "StreamWithdrawn"
  ): TypedContractEvent<
    StreamWithdrawnEvent.InputTuple,
    StreamWithdrawnEvent.OutputTuple,
    StreamWithdrawnEvent.OutputObject
  >;

  filters: {
    "AgentPayment(address,address,uint256)": TypedContractEvent<
      AgentPaymentEvent.InputTuple,
      AgentPaymentEvent.OutputTuple,
      AgentPaymentEvent.OutputObject
    >;
    AgentPayment: TypedContractEvent<
      AgentPaymentEvent.InputTuple,
      AgentPaymentEvent.OutputTuple,
      AgentPaymentEvent.OutputObject
    >;

    "AgentRegistered(address,string,uint256)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentUpdated(address,uint256,bool)": TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
    AgentUpdated: TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;

    "BatchSettled(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      BatchSettledEvent.InputTuple,
      BatchSettledEvent.OutputTuple,
      BatchSettledEvent.OutputObject
    >;
    BatchSettled: TypedContractEvent<
      BatchSettledEvent.InputTuple,
      BatchSettledEvent.OutputTuple,
      BatchSettledEvent.OutputObject
    >;

    "FeesWithdrawn(address,uint256)": TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;
    FeesWithdrawn: TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;

    "StreamCancelled(uint256,address,uint256)": TypedContractEvent<
      StreamCancelledEvent.InputTuple,
      StreamCancelledEvent.OutputTuple,
      StreamCancelledEvent.OutputObject
    >;
    StreamCancelled: TypedContractEvent<
      StreamCancelledEvent.InputTuple,
      StreamCancelledEvent.OutputTuple,
      StreamCancelledEvent.OutputObject
    >;

    "StreamCreated(uint256,address,address,uint256,uint64,uint64)": TypedContractEvent<
      StreamCreatedEvent.InputTuple,
      StreamCreatedEvent.OutputTuple,
      StreamCreatedEvent.OutputObject
    >;
    StreamCreated: TypedContractEvent<
      StreamCreatedEvent.InputTuple,
      StreamCreatedEvent.OutputTuple,
      StreamCreatedEvent.OutputObject
    >;

    "StreamWithdrawn(uint256,address,uint256)": TypedContractEvent<
      StreamWithdrawnEvent.InputTuple,
      StreamWithdrawnEvent.OutputTuple,
      StreamWithdrawnEvent.OutputObject
    >;
    StreamWithdrawn: TypedContractEvent<
      StreamWithdrawnEvent.InputTuple,
      StreamWithdrawnEvent.OutputTuple,
      StreamWithdrawnEvent.OutputObject
    >;
  };
}
