import { ethers, network } from "hardhat";
import * as fs from "fs";
import * as path from "path";

// Arc testnet ERC20 USDC — system contract (NOT Base Sepolia address)
const USDC_ADDRESS = process.env.USDC_ADDRESS || "0x3600000000000000000000000000000000000000";

async function main() {
  const [deployer] = await ethers.getSigners();

  console.log("\n╔══════════════════════════════════════╗");
  console.log("║        FLUX DEPLOYMENT                ║");
  console.log("╚══════════════════════════════════════╝\n");
  console.log(`Network:    ${network.name}`);
  console.log(`Deployer:   ${deployer.address}`);
  console.log(`USDC:       ${USDC_ADDRESS}\n`);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log(`Balance:    ${ethers.formatUnits(balance, 6)} USDC\n`);

  const FluxSettlement = await ethers.getContractFactory("FluxSettlement");

  let flux: any = null;
  for (let attempt = 1; attempt <= 10; attempt++) {
    try {
      console.log(`Deploying FluxSettlement... (attempt ${attempt}/10)`);
      flux = await FluxSettlement.deploy(USDC_ADDRESS);
      break; // success
    } catch (err: any) {
      const msg = err?.message || "";
      if (msg.includes("txpool is full") || msg.includes("replacement transaction underpriced")) {
        console.log(`  txpool full — waiting 20s...`);
        await new Promise(r => setTimeout(r, 20_000));
      } else {
        throw err;
      }
    }
  }

  if (!flux) throw new Error("Deploy failed after 10 attempts — try again later.");

  await flux.waitForDeployment();
  const address = await flux.getAddress();

  console.log(`\n✓ FluxSettlement deployed to: ${address}`);
  console.log(`  Explorer: https://testnet.arcscan.app/address/${address}\n`);

  // Save deployment JSON
  const deployDir = path.join(__dirname, "..", "deployments");
  if (!fs.existsSync(deployDir)) fs.mkdirSync(deployDir, { recursive: true });
  fs.writeFileSync(
    path.join(deployDir, `${network.name}.json`),
    JSON.stringify({ FluxSettlement: address, USDC: USDC_ADDRESS, deployer: deployer.address, timestamp: new Date().toISOString() }, null, 2)
  );

  // Auto-write frontend/.env.local
  const envPath = path.join(__dirname, "..", "frontend", ".env.local");
  fs.writeFileSync(envPath,
    `# Auto-generated by deploy script\n` +
    `NEXT_PUBLIC_FLUX_ADDRESS=${address}\n` +
    `NEXT_PUBLIC_USDC_ADDRESS=${USDC_ADDRESS}\n` +
    `NEXT_PUBLIC_CHAIN_ID=5042002\n` +
    `NEXT_PUBLIC_RPC_URL=https://rpc.testnet.arc.network\n` +
    `NEXT_PUBLIC_EXPLORER_URL=https://testnet.arcscan.app\n`
  );

  console.log(`✓ frontend/.env.local auto-updated\n`);
  console.log("══════════════════════════════════════");
  console.log("  DEPLOYMENT COMPLETE");
  console.log(`  Contract: ${address}`);
  console.log("══════════════════════════════════════\n");
}

main().catch((e) => { console.error(e); process.exitCode = 1; });